version: "3.8"

services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crawler
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs/crawler:/app/logs
    ports:
      - "3005:3005"
      - "50051:50051"